  
language: python
python:
  - "2.7"
install:
  - pip install robotframework
  - pip install robotframework-selenium2library==1.8.0
script:
- "python test/run_test.py"
 install:
    - pip install -r requirements.txt

   script:
    - py.test  --cov-report term --cov=app/test/

   env:
    - CODECOV_TOKEN='b1f892d5-16d6-4c81-8f33-41c20a6774ca'

   after_success:
    - codecov